server:
  port: 8002
spring:
  application:
    name: yin-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: payment_routh
#          uri: http://localhost:8090
#          predicates:
#            - Path=/api/**
#          filters:
#            - StripPrefix=0
    nacos:
      discovery:
        server-addr: localhost:8848 #服务注册中心地址
      #        server-addr: 192.168.137.150:1111
#      config:
#        server-addr: localhost:8848 #配置中心地址
        #        server-addr: 192.168.137.150:1111 #配置中心地址
#        file-extension: yaml #指定yaml格式的配置（yml和yaml都可以）
        #        group: DEFAULT_GROUP
#        namespace: acd11217-3c95-4f9d-a585-42af69df36ea

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者【可选】，
#注意：nacos-payment-provider含有IP和端口)
service-url:
  gateway-service-url: http://springboot-init11111

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

