server:
  port: 8002

spring:
  application:
    name: yin-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: http://localhost:8090
          predicates:
            - Path=/api/**


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者【可选】，
#注意：nacos-payment-provider含有IP和端口)
service-url:
  gateway-service-url: http://springboot-init11111

dubbo:
  #当前应用名字
  application:
    name: consumer-server
  #注册中心地址

  registry:
    address: zookeeper://127.0.0.1:2181



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions=DEBUG:

